In [1]:
import tensorflow as tf

# Merge and Split

## Merge
1. tf.concat(`tensors`, `axis`): merge tensors along one axis, retrun a matrix with the same dimension as `tensors`.

In [3]:
a = tf.random.normal([1, 2, 3])
b = tf.random.normal([3, 2, 3])
tf.concat([a, b], axis=0)

<tf.Tensor: id=25, shape=(4, 2, 3), dtype=float32, numpy=
array([[[-1.1082327 , -0.08649035,  0.27399915],
        [-1.1045202 ,  0.4650352 , -0.6743147 ]],

       [[ 1.4760798 , -0.47368196,  0.16437604],
        [ 0.43834966,  1.0096303 ,  0.69791526]],

       [[ 0.05899262,  0.27281964,  1.1837143 ],
        [-1.2886252 ,  0.5828275 ,  1.0456228 ]],

       [[ 0.55681574, -0.13984832, -0.11849394],
        [-1.2375274 , -1.2442293 , -0.45300415]]], dtype=float32)>

2. tf.stack(`tensors`, `axis_number`): merge tensors and create a new dimension at index = `axis_number`, so the result will be n+1 dimensions.

In [4]:
a = tf.random.normal([35, 8])
b = tf.random.normal([35, 8])
tf.stack([a, b], axis=0)

<tf.Tensor: id=38, shape=(2, 35, 8), dtype=float32, numpy=
array([[[-9.18164253e-01,  6.59261569e-02, -5.25394678e-02,
         -6.09942377e-02,  7.01764703e-01,  9.24700320e-01,
         -8.21399450e-01,  3.62015784e-01],
        [-7.05300212e-01, -6.61355317e-01,  2.47126833e-01,
          4.38659042e-01,  1.06069398e+00, -1.83120596e+00,
          1.14760804e+00, -2.60136664e-01],
        [-2.58656907e+00,  1.88450068e-01, -1.36849031e-01,
         -1.59143412e+00,  1.41065264e+00, -4.09282669e-02,
          6.88498974e-01, -1.13005131e-01],
        [ 1.29933751e+00,  8.07327867e-01,  6.05076969e-01,
         -2.55173612e+00, -4.38068777e-01, -2.81167567e-01,
         -7.50690103e-01,  7.58304894e-01],
        [-8.58890593e-01, -6.39792204e-01,  2.10800275e-01,
          2.01897264e-01,  5.26551545e-01, -2.30341101e+00,
          2.57313222e-01,  2.10787463e+00],
        [ 1.99092352e+00,  2.80129194e-01,  2.36539316e+00,
          3.29759985e-01,  2.22626150e-01,  2.96318442e-01,
 

## Split
1. tf.split(x, `axis`, `number of split results`)

In [5]:
x = tf.random.normal([10, 5, 3])

In [7]:
result = tf.split(x, axis=0, num_or_size_splits=10)
len(result)

10

In [8]:
result[0]

<tf.Tensor: id=59, shape=(1, 5, 3), dtype=float32, numpy=
array([[[-0.8347531 , -1.456611  ,  0.8897907 ],
        [ 0.4380629 , -0.15589885,  0.78215843],
        [ 0.73904943, -2.5745983 , -0.5020329 ],
        [ 0.1347836 , -2.45452   , -0.653758  ],
        [ 1.0681955 , -1.7326038 ,  0.8301812 ]]], dtype=float32)>

2. tf.unstack(x, `axis`)

In [9]:
result = tf.unstack(x, axis=0)
len(result)

10

# Statistics
## Vector norm
### L1 norm
$$||\vec{x}||_1 = \sum_{i} |x_i|$$

### L2 norm
$$ ||\vec{x}||_2 = \sqrt{\sum_{i}{x_i}^2} $$

### $\infty$ norm
$$ ||\vec{x}||_{\infty}= max_{i}(|x_i|) $$

In [10]:
x = tf.ones([3,3])

In [11]:
# L1 norm
tf.norm(x, ord=1)

<tf.Tensor: id=85, shape=(), dtype=float32, numpy=9.0>

In [12]:
# L2 norm
tf.norm(x, ord=2)

<tf.Tensor: id=90, shape=(), dtype=float32, numpy=3.0>

In [13]:
# Infinity norm
import numpy as np
tf.norm(x, ord=np.inf)

<tf.Tensor: id=94, shape=(), dtype=float32, numpy=1.0>

## Description

In [14]:
x = tf.random.normal([4, 10])

### Max and Min

In [15]:
tf.reduce_max(x, axis=1)

<tf.Tensor: id=102, shape=(4,), dtype=float32, numpy=array([0.50672686, 0.8440412 , 1.3618019 , 1.801574  ], dtype=float32)>

In [16]:
tf.reduce_max(x)

<tf.Tensor: id=104, shape=(), dtype=float32, numpy=1.801574>

In [17]:
tf.reduce_min(x, axis=0)

<tf.Tensor: id=106, shape=(10,), dtype=float32, numpy=
array([-1.2080202 , -0.4390637 , -1.0561498 , -1.2111022 , -0.4704426 ,
       -0.36321747, -0.77497   , -0.7781316 , -1.0217596 , -0.318466  ],
      dtype=float32)>

In [18]:
tf.reduce_min(x)

<tf.Tensor: id=108, shape=(), dtype=float32, numpy=-1.2111022>

### Index Max and Min

In [25]:
tf.argmax(x, axis=1)

<tf.Tensor: id=118, shape=(4,), dtype=int64, numpy=array([5, 9, 4, 4], dtype=int64)>

In [26]:
tf.argmin(x, axis=0)

<tf.Tensor: id=120, shape=(10,), dtype=int64, numpy=array([0, 0, 0, 2, 0, 1, 0, 2, 0, 0], dtype=int64)>

### Mean

In [19]:
tf.reduce_mean(x, axis=1)

<tf.Tensor: id=110, shape=(4,), dtype=float32, numpy=array([-0.6473968 , -0.07483584,  0.02938275,  0.17580307], dtype=float32)>

In [21]:
tf.reduce_mean(x)

<tf.Tensor: id=112, shape=(), dtype=float32, numpy=-0.1292617>

### Sum

In [22]:
tf.reduce_sum(x, axis=1)

<tf.Tensor: id=114, shape=(4,), dtype=float32, numpy=array([-6.473968  , -0.74835837,  0.29382747,  1.7580307 ], dtype=float32)>

In [23]:
tf.reduce_sum(x)

<tf.Tensor: id=116, shape=(), dtype=float32, numpy=-5.170468>

# Comparison
tf.equal(`x`, `y`)

In [27]:
x = tf.random.normal([100, 10])
x = tf.nn.softmax(x, axis=1)
x = tf.argmax(x, axis=1)
x

<tf.Tensor: id=129, shape=(100,), dtype=int64, numpy=
array([5, 3, 8, 9, 8, 3, 1, 3, 3, 2, 1, 8, 0, 3, 6, 2, 2, 3, 5, 8, 4, 1,
       4, 4, 6, 4, 7, 4, 7, 3, 3, 4, 1, 8, 1, 0, 2, 7, 5, 7, 6, 6, 6, 6,
       9, 7, 3, 3, 7, 9, 5, 6, 6, 9, 2, 9, 8, 9, 7, 3, 9, 5, 4, 3, 8, 3,
       6, 0, 9, 8, 7, 7, 3, 7, 2, 4, 8, 3, 6, 0, 4, 0, 4, 6, 1, 8, 6, 5,
       4, 6, 5, 9, 6, 0, 9, 6, 9, 8, 5, 0], dtype=int64)>

In [29]:
y = tf.random.uniform([100], dtype=tf.int64, maxval=10)
y

<tf.Tensor: id=133, shape=(100,), dtype=int64, numpy=
array([8, 2, 6, 0, 4, 6, 5, 0, 3, 5, 7, 2, 2, 4, 2, 4, 6, 4, 7, 8, 9, 8,
       7, 8, 3, 2, 5, 2, 8, 1, 2, 2, 5, 1, 2, 4, 4, 2, 9, 0, 4, 2, 0, 2,
       2, 6, 0, 6, 1, 0, 5, 6, 7, 4, 1, 6, 4, 9, 2, 9, 3, 8, 4, 1, 5, 3,
       3, 3, 1, 0, 3, 9, 4, 1, 9, 4, 4, 2, 1, 6, 7, 9, 6, 5, 8, 6, 7, 4,
       0, 6, 8, 5, 8, 6, 7, 3, 0, 5, 2, 5], dtype=int64)>

In [30]:
tf.equal(x, y)

<tf.Tensor: id=134, shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False])>

In [31]:
tf.math.greater(x, y)

<tf.Tensor: id=135, shape=(100,), dtype=bool, numpy=
array([False,  True,  True,  True,  True, False, False,  True, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True, False,  True, False, False,
        True,  True, False,  True, False,  True,  True,  True, False,
       False,  True, False, False,  True,  True,  True, False, False,
       False, False,  True, False,  True, False,  True,  True, False,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False])>

In [33]:
tf.math.less(x, y)

<tf.Tensor: id=136, shape=(100,), dtype=bool, numpy=
array([ True, False, False, False, False,  True,  True, False, False,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False,  True, False, False, False, False,  True,  True,
        True,  True, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
        True])>

In [34]:
tf.math.greater_equal(x, y)

<tf.Tensor: id=137, shape=(100,), dtype=bool, numpy=
array([False,  True,  True,  True,  True, False, False,  True,  True,
       False, False,  True, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False])>

In [35]:
tf.math.less_equal(x, y)

<tf.Tensor: id=138, shape=(100,), dtype=bool, numpy=
array([ True, False, False, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True,  True,  True, False,
       False, False, False,  True, False,  True, False,  True,  True,
       False, False,  True, False,  True, False, False, False,  True,
        True, False,  True,  True, False, False, False,  True,  True,
        True,  True, False,  True, False,  True, False, False,  True,
        True, False,  True,  True, False, False, False, False, False,
        True])>

In [39]:
tf.math.not_equal(x, y)

<tf.Tensor: id=141, shape=(100,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])>

# Padding and Duplicate

## Padding
tf.pad(`x`, `paddings`)

Syntax: paddings = [[Left padding, Righr Padding], ...]

In [40]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([7,8,9,1])

In [41]:
b = tf.pad(b, [[0,2]])
b

<tf.Tensor: id=145, shape=(6,), dtype=int32, numpy=array([7, 8, 9, 1, 0, 0])>

## Duplicate
tf.tile(x, `mutiples`)