In [1]:
import tensorflow as tf

# Data types
- Numerical
- String
- Boolean

## Numerical type
- Scalar: zero-demensional data, shape=[]
- Vector: one-demensional data, shape=[n]
- Matrix: two-demenstional data, shape=[n,m]
- Tensor: array with more than 2 demensions

In `tensorflow`, the term `tensor` contains scalar, vector, matrix and tensor.

### Create a tensor

#### Scalar

In [4]:
a = 1.2
aa = tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

You can:
1. Inspect a tensor by directly calling it or print().
2. Get the data by numpy()

In [5]:
aa

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=1.2>

In [6]:
aa.numpy()

1.2

#### Vector
You must use brakets to create a tensor with >1 demensions.

In [8]:
a = tf.constant([1.2])
a, a.shape

(<tf.Tensor: id=3, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

#### Matrix

In [11]:
a = tf.constant([[1, 2], [3., 4]])
a, a.shape

(<tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>, TensorShape([2, 2]))

#### Tensor

In [13]:
a = tf.constant([[[1, 2], [3., 4]], [[5, 6], [7, 8]]])
a, a.shape

(<tf.Tensor: id=6, shape=(2, 2, 2), dtype=float32, numpy=
 array([[[1., 2.],
         [3., 4.]],
 
        [[5., 6.],
         [7., 8.]]], dtype=float32)>, TensorShape([2, 2, 2]))

## String

In [14]:
a = tf.constant("Hello World")
a

<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'Hello World'>

Some commenly used string functions could also be available in string tensors.

In [18]:
tf.strings.lower(a)

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'hello world'>

## Boolean

In [19]:
a = tf.constant(True)
a

<tf.Tensor: id=9, shape=(), dtype=bool, numpy=True>

**Waring: boolean tensor is not boolean datatype of python!**

In [26]:
a is True

False

# Precision of tensor

- Tensor could be saved as 16-bit, 32-bit and 64-bit, of which tf.float64 is same as tf.double.
- Data may cause overflow if the precision is too small.
- High precision tensor can save more decimals but takes more memory

In [28]:
a = tf.constant(123456789, dtype=tf.int16)
b = tf.constant(123456789, dtype=tf.int32)
a, b

(<tf.Tensor: id=18, shape=(), dtype=int16, numpy=-13035>,
 <tf.Tensor: id=19, shape=(), dtype=int32, numpy=123456789>)

In [30]:
import numpy as np

a = tf.constant(np.pi, dtype=tf.float32)
b = tf.constant(np.pi, dtype=tf.float64)

a, b

(<tf.Tensor: id=20, shape=(), dtype=float32, numpy=3.1415927>,
 <tf.Tensor: id=21, shape=(), dtype=float64, numpy=3.141592653589793>)

### Transfer the datatype

1. Numerical to Numerical

In [35]:
print(a)
tf.cast(a, tf.double)
a

tf.Tensor(3.1415927, shape=(), dtype=float32)


<tf.Tensor: id=20, shape=(), dtype=float32, numpy=3.1415927>

In [39]:
a = tf.constant(np.pi, dtype=tf.float16)
a = tf.cast(a, tf.float64)
a

<tf.Tensor: id=31, shape=(), dtype=float64, numpy=3.140625>

**Warning: data may overflow when transfer from high to low precision**

In [41]:
a = tf.constant(123456789, dtype=tf.int32)
a = tf.cast(a, tf.int16)
a

<tf.Tensor: id=35, shape=(), dtype=int16, numpy=-13035>

2. Boolean and numerical

In [42]:
a =tf.constant([True, False])
a = tf.cast(a, tf.int32)
a

<tf.Tensor: id=37, shape=(2,), dtype=int32, numpy=array([1, 0])>

In [43]:
a = tf.constant([0, 1, 2, -1])
a = tf.cast(a, tf.bool)
a

<tf.Tensor: id=39, shape=(4,), dtype=bool, numpy=array([False,  True,  True,  True])>

# Tensor and variable

Variable is a subclass of tensor, `Tensorflow` will watch and calculate every variable's gradient during traing. So you need to set only the weights you are interested in as variables.

In [44]:
a = tf.constant([0, 1, 2, -1])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

# Create a tensor

## 1. From `Numpy`, `List` object (The same as tf.constant())

- From `list`

In [45]:
tf.convert_to_tensor([1, 2]) 

<tf.Tensor: id=48, shape=(2,), dtype=int32, numpy=array([1, 2])>

- From `numpy` array: 

    **When converted to `tensor`, all `numpy` array will be transfered to 64-bit !!**

In [47]:
tf.convert_to_tensor(np.array([1,2.]))

<tf.Tensor: id=50, shape=(2,), dtype=float64, numpy=array([1., 2.])>

In [51]:
tf.convert_to_tensor(np.array([1,2]))

<tf.Tensor: id=51, shape=(2,), dtype=int32, numpy=array([1, 2])>

## 2. Create zero metrix or all-one metrix
tf.zeros( `shape` )

tf.ones( `shape` )

In [52]:
tf.zeros([2, 2]), tf.ones([2, 3])

(<tf.Tensor: id=54, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: id=57, shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

tf.zeros_like( `tensor` )

tf.ones_like( `tensor` )

In [53]:
a = tf.zeros([2, 3])
tf.ones_like(a)

<tf.Tensor: id=63, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## 3. Create all-same-number metrix
tf.fill(`shape`, `vlaue`)

In [54]:
tf.fill([3,2],-1)

<tf.Tensor: id=66, shape=(3, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1],
       [-1, -1]])>