In [1]:
import tensorflow as tf

# Data types
- Numerical
- String
- Boolean

## Numerical type
- Scalar: zero-demensional data, shape=[]
- Vector: one-demensional data, shape=[n]
- Matrix: two-demenstional data, shape=[n,m]
- Tensor: array with more than 2 demensions

In `tensorflow`, the term `tensor` contains scalar, vector, matrix and tensor.

### Create a tensor

#### Scalar

In [4]:
a = 1.2
aa = tf.constant(1.2)
type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

You can:
1. Inspect a tensor by directly calling it or print().
2. Get the data by numpy()

In [5]:
aa

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=1.2>

In [6]:
aa.numpy()

1.2

#### Vector
You must use brakets to create a tensor with >1 demensions.

In [8]:
a = tf.constant([1.2])
a, a.shape

(<tf.Tensor: id=3, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

#### Matrix

In [11]:
a = tf.constant([[1, 2], [3., 4]])
a, a.shape

(<tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>, TensorShape([2, 2]))

#### Tensor

In [13]:
a = tf.constant([[[1, 2], [3., 4]], [[5, 6], [7, 8]]])
a, a.shape

(<tf.Tensor: id=6, shape=(2, 2, 2), dtype=float32, numpy=
 array([[[1., 2.],
         [3., 4.]],
 
        [[5., 6.],
         [7., 8.]]], dtype=float32)>, TensorShape([2, 2, 2]))

## String

In [14]:
a = tf.constant("Hello World")
a

<tf.Tensor: id=7, shape=(), dtype=string, numpy=b'Hello World'>

Some commenly used string functions could also be available in string tensors.

In [18]:
tf.strings.lower(a)

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'hello world'>

## Boolean

In [19]:
a = tf.constant(True)
a

<tf.Tensor: id=9, shape=(), dtype=bool, numpy=True>

**Waring: boolean tensor is not boolean datatype of python!**

In [26]:
a is True

False

# Precision of tensor

- Tensor could be saved as 16-bit, 32-bit and 64-bit, of which tf.float64 is same as tf.double.
- Data may cause overflow if the precision is too small.
- High precision tensor can save more decimals but takes more memory

In [28]:
a = tf.constant(123456789, dtype=tf.int16)
b = tf.constant(123456789, dtype=tf.int32)
a, b

(<tf.Tensor: id=18, shape=(), dtype=int16, numpy=-13035>,
 <tf.Tensor: id=19, shape=(), dtype=int32, numpy=123456789>)

In [30]:
import numpy as np

a = tf.constant(np.pi, dtype=tf.float32)
b = tf.constant(np.pi, dtype=tf.float64)

a, b

(<tf.Tensor: id=20, shape=(), dtype=float32, numpy=3.1415927>,
 <tf.Tensor: id=21, shape=(), dtype=float64, numpy=3.141592653589793>)

### Transfer the datatype

1. Numerical to Numerical

In [35]:
print(a)
tf.cast(a, tf.double)
a

tf.Tensor(3.1415927, shape=(), dtype=float32)


<tf.Tensor: id=20, shape=(), dtype=float32, numpy=3.1415927>

In [39]:
a = tf.constant(np.pi, dtype=tf.float16)
a = tf.cast(a, tf.float64)
a

<tf.Tensor: id=31, shape=(), dtype=float64, numpy=3.140625>

**Warning: data may overflow when transfer from high to low precision**

In [41]:
a = tf.constant(123456789, dtype=tf.int32)
a = tf.cast(a, tf.int16)
a

<tf.Tensor: id=35, shape=(), dtype=int16, numpy=-13035>

2. Boolean and numerical

In [42]:
a =tf.constant([True, False])
a = tf.cast(a, tf.int32)
a

<tf.Tensor: id=37, shape=(2,), dtype=int32, numpy=array([1, 0])>

In [43]:
a = tf.constant([0, 1, 2, -1])
a = tf.cast(a, tf.bool)
a

<tf.Tensor: id=39, shape=(4,), dtype=bool, numpy=array([False,  True,  True,  True])>

# Tensor and variable

Variable is a subclass of tensor, `Tensorflow` will watch and calculate every variable's gradient during traing. So you need to set only the weights you are interested in as variables.

In [44]:
a = tf.constant([0, 1, 2, -1])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

# Create a tensor

## 1. From `Numpy`, `List` object (The same as tf.constant())

- From `list`

In [45]:
tf.convert_to_tensor([1, 2]) 

<tf.Tensor: id=48, shape=(2,), dtype=int32, numpy=array([1, 2])>

- From `numpy` array: 

    **When converted to `tensor`, all `numpy` array will be transfered to 64-bit !!**

In [47]:
tf.convert_to_tensor(np.array([1,2.]))

<tf.Tensor: id=50, shape=(2,), dtype=float64, numpy=array([1., 2.])>

In [51]:
tf.convert_to_tensor(np.array([1,2]))

<tf.Tensor: id=51, shape=(2,), dtype=int32, numpy=array([1, 2])>

## 2. Create zero metrix or all-one metrix
tf.zeros( `shape` )

tf.ones( `shape` )

In [52]:
tf.zeros([2, 2]), tf.ones([2, 3])

(<tf.Tensor: id=54, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: id=57, shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

tf.zeros_like( `tensor` )

tf.ones_like( `tensor` )

In [53]:
a = tf.zeros([2, 3])
tf.ones_like(a)

<tf.Tensor: id=63, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## 3. Create all-same-number metrix
tf.fill(`shape`, `vlaue`)

In [55]:
tf.fill([3,2],-1)

<tf.Tensor: id=69, shape=(3, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1],
       [-1, -1]])>

## 4. Create matrix with distribution

- Normal Distribution

tf.random.normal( `shape` )

In [56]:
tf.random.normal([2,5])

<tf.Tensor: id=75, shape=(2, 5), dtype=float32, numpy=
array([[-0.7132531 , -0.7652995 , -0.18228582, -0.54958737, -0.14978345],
       [-0.20682947,  0.60895646,  0.3859338 ,  1.9758793 , -0.2656213 ]],
      dtype=float32)>

- Uniform Distribution

tf.random.uniform( `shape` )

In [60]:
tf.random.uniform([2, 5], minval=0, maxval=None, dtype=tf.float32)

<tf.Tensor: id=96, shape=(2, 5), dtype=float32, numpy=
array([[0.51591   , 0.5870291 , 0.8813374 , 0.9221803 , 0.02356362],
       [0.45910466, 0.08149767, 0.7368306 , 0.23610973, 0.6914693 ]],
      dtype=float32)>

In [61]:
tf.random.uniform([2, 5], minval=0, maxval=10, dtype=tf.float32)

<tf.Tensor: id=103, shape=(2, 5), dtype=float32, numpy=
array([[0.27811408, 4.749919  , 7.690363  , 4.1043115 , 1.4213097 ],
       [7.5546846 , 0.16406775, 4.3657827 , 1.8190694 , 0.87766886]],
      dtype=float32)>

In [62]:
tf.random.uniform([2, 5], minval=0, maxval=100, dtype=tf.int32)

<tf.Tensor: id=107, shape=(2, 5), dtype=int32, numpy=
array([[54, 63, 79, 62, 76],
       [51, 24, 48, 88, 66]])>

## 5. Range

In [63]:
tf.range(10)

<tf.Tensor: id=111, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [65]:
tf.range(0,10, delta=2)

<tf.Tensor: id=119, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

# Index and Slice

In [66]:
x = tf.random.normal([4, 32, 32, 3])

In [67]:
# [i][j]...[k]
x[0][1][2]

<tf.Tensor: id=137, shape=(3,), dtype=float32, numpy=array([-0.9562797 , -0.4330293 , -0.09569128], dtype=float32)>

In [70]:
# [start: end: step]
x[1:3, ::2, 1]

<tf.Tensor: id=149, shape=(2, 16, 3), dtype=float32, numpy=
array([[[-1.9995172e-01,  4.5738104e-01, -5.5812371e-01],
        [-3.4855106e-01, -2.3644443e+00,  6.8523449e-01],
        [ 1.4028171e+00,  2.1183555e+00, -6.7102455e-02],
        [-7.7778375e-01,  1.2040956e+00,  5.3549552e-01],
        [-8.3283961e-01, -8.3894230e-02, -1.1766382e+00],
        [ 3.9340559e-01, -3.1565198e-01, -1.0303822e+00],
        [-5.0492215e-01,  3.7193766e-01,  1.0776414e+00],
        [-7.2879612e-01, -9.6958661e-01,  2.7768111e-01],
        [ 1.7403409e+00, -5.4005045e-01,  2.3048544e-02],
        [ 3.7017575e-01, -1.1732317e+00,  3.6550251e-01],
        [-1.6159126e+00, -1.4579494e-02,  9.4458348e-01],
        [ 6.4091134e-01, -1.3970420e+00, -1.4650918e+00],
        [-5.3637135e-01,  1.1479491e+00, -3.0519328e-01],
        [ 8.6265528e-01,  8.0218956e-02,  1.7532107e+00],
        [ 6.1943299e-01, -4.6817672e-01,  8.0162120e-01],
        [ 7.2510734e-02,  1.2340344e-01, -9.2612374e-01]],

       [[-

In [71]:
# [a, ..., n]
x[0:2, ..., 1:]

<tf.Tensor: id=153, shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[ 1.2567059 , -0.05661172],
         [-0.297681  , -1.0001436 ],
         [-0.43508968,  0.28859165],
         ...,
         [ 1.5331815 ,  1.2004473 ],
         [-0.05894696,  0.67103326],
         [ 0.36110863, -1.320561  ]],

        [[ 0.07739259, -0.26365814],
         [ 1.3755002 , -0.54674125],
         [-0.4330293 , -0.09569128],
         ...,
         [-0.1660166 ,  1.0824121 ],
         [-0.6880442 ,  0.9108166 ],
         [ 1.1363962 ,  0.7534359 ]],

        [[ 2.229655  , -0.39732864],
         [-1.2506667 ,  0.30396736],
         [ 1.155661  ,  0.49625996],
         ...,
         [ 0.49630174,  0.24248329],
         [-0.1899775 , -1.3538915 ],
         [-0.11768356,  1.084095  ]],

        ...,

        [[-0.69373286, -0.45770675],
         [-1.4228247 ,  1.4420824 ],
         [-0.05187436,  0.4801624 ],
         ...,
         [ 1.1509464 ,  0.15331566],
         [-1.299957  , -0.9127746 ],
         

# Demension conversion
- reshape
- expand-dims
- squeeze
- transpose
- tile

## Reshape

tf.reshape(x, `new shape`)

In [72]:
x = tf.range(96)
x = tf.reshape(x, [2, 4, 4, 3])
x

<tf.Tensor: id=159, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [75]:
# -1: automatically reshape
x = tf.reshape(x, [2, -1])
x 

<tf.Tensor: id=163, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

## Expand dimension and delete dimension

In [76]:
x = tf.expand_dims(x, axis=0)
x

<tf.Tensor: id=165, shape=(1, 2, 48), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
         64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
         80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [77]:
x  =tf.squeeze(x, axis=0)

In [78]:
x

<tf.Tensor: id=166, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

# Transpose
tf.traspose(x, `dimension_index`)

In [79]:
x = tf.random.normal([2,4,6,8])

In [80]:
tf.transpose(x, [0,2,1,3])

<tf.Tensor: id=174, shape=(2, 6, 4, 8), dtype=float32, numpy=
array([[[[ 1.93896309e-01,  6.73287690e-01, -2.43092823e+00,
          -6.01112068e-01, -1.19187272e+00, -1.35867327e-01,
           1.74045756e-01, -1.75828055e-01],
         [-4.10754859e-01, -3.52823019e-01,  1.70613265e+00,
          -1.51721403e-01, -1.04232216e+00,  1.82088709e+00,
          -1.14320982e+00,  3.02172899e-01],
         [-1.39251113e-01, -2.12520719e+00, -1.66117713e-01,
          -1.07224095e+00,  2.01991963e+00,  1.14400065e+00,
           2.18173003e+00, -5.96713543e-01],
         [ 2.06526056e-01, -4.41175587e-02, -6.42478526e-01,
          -2.63251930e-01, -6.12135053e-01, -4.30338055e-01,
          -2.38895401e-01, -4.13985044e-01]],

        [[-2.74962902e-01,  1.10465419e+00,  2.41194293e-01,
          -7.75023878e-01, -2.63579756e-01,  7.98629940e-01,
           4.70934063e-01,  4.09947224e-02],
         [-1.54915020e-01,  4.48311746e-01, -1.43304181e+00,
           1.57208252e+00,  1.46619394e-

# Duplicate
tf.tile(x, `multiples_of_each_line`)

In [81]:
b= tf.tile(x, multiples=[1,2,1,1])
b.shape

TensorShape([2, 8, 6, 8])

# Matrix multiplication

In [2]:
a = tf.random.normal([2,3])
b = tf.random.normal([3,2])

In [3]:
a, b

(<tf.Tensor: id=5, shape=(2, 3), dtype=float32, numpy=
 array([[-0.5207022 ,  0.7372688 , -0.08357619],
        [ 0.9145156 , -0.23434299,  0.64583147]], dtype=float32)>,
 <tf.Tensor: id=11, shape=(3, 2), dtype=float32, numpy=
 array([[-0.24423122, -2.1923692 ],
        [-0.19927609,  1.7218969 ],
        [-0.43838584,  1.9741828 ]], dtype=float32)>)

In [7]:
a@b

<tf.Tensor: id=15, shape=(2, 2), dtype=float32, numpy=
array([[ 0.0168903 ,  2.2460775 ],
       [-0.45977768, -1.1334808 ]], dtype=float32)>