In [1]:
import tensorflow as tf

# Merge and Split

## Merge
1. tf.concat(`tensors`, `axis`): merge tensors along one axis, retrun a matrix with the same dimension as `tensors`.

In [3]:
a = tf.random.normal([1, 2, 3])
b = tf.random.normal([3, 2, 3])
tf.concat([a, b], axis=0)

<tf.Tensor: id=25, shape=(4, 2, 3), dtype=float32, numpy=
array([[[-1.1082327 , -0.08649035,  0.27399915],
        [-1.1045202 ,  0.4650352 , -0.6743147 ]],

       [[ 1.4760798 , -0.47368196,  0.16437604],
        [ 0.43834966,  1.0096303 ,  0.69791526]],

       [[ 0.05899262,  0.27281964,  1.1837143 ],
        [-1.2886252 ,  0.5828275 ,  1.0456228 ]],

       [[ 0.55681574, -0.13984832, -0.11849394],
        [-1.2375274 , -1.2442293 , -0.45300415]]], dtype=float32)>

2. tf.stack(`tensors`, `axis_number`): merge tensors and create a new dimension at index = `axis_number`, so the result will be n+1 dimensions.

In [4]:
a = tf.random.normal([35, 8])
b = tf.random.normal([35, 8])
tf.stack([a, b], axis=0)

<tf.Tensor: id=38, shape=(2, 35, 8), dtype=float32, numpy=
array([[[-9.18164253e-01,  6.59261569e-02, -5.25394678e-02,
         -6.09942377e-02,  7.01764703e-01,  9.24700320e-01,
         -8.21399450e-01,  3.62015784e-01],
        [-7.05300212e-01, -6.61355317e-01,  2.47126833e-01,
          4.38659042e-01,  1.06069398e+00, -1.83120596e+00,
          1.14760804e+00, -2.60136664e-01],
        [-2.58656907e+00,  1.88450068e-01, -1.36849031e-01,
         -1.59143412e+00,  1.41065264e+00, -4.09282669e-02,
          6.88498974e-01, -1.13005131e-01],
        [ 1.29933751e+00,  8.07327867e-01,  6.05076969e-01,
         -2.55173612e+00, -4.38068777e-01, -2.81167567e-01,
         -7.50690103e-01,  7.58304894e-01],
        [-8.58890593e-01, -6.39792204e-01,  2.10800275e-01,
          2.01897264e-01,  5.26551545e-01, -2.30341101e+00,
          2.57313222e-01,  2.10787463e+00],
        [ 1.99092352e+00,  2.80129194e-01,  2.36539316e+00,
          3.29759985e-01,  2.22626150e-01,  2.96318442e-01,
 

## Split
1. tf.split(x, `axis`, `number of split results`)

In [5]:
x = tf.random.normal([10, 5, 3])

In [7]:
result = tf.split(x, axis=0, num_or_size_splits=10)
len(result)

10

In [8]:
result[0]

<tf.Tensor: id=59, shape=(1, 5, 3), dtype=float32, numpy=
array([[[-0.8347531 , -1.456611  ,  0.8897907 ],
        [ 0.4380629 , -0.15589885,  0.78215843],
        [ 0.73904943, -2.5745983 , -0.5020329 ],
        [ 0.1347836 , -2.45452   , -0.653758  ],
        [ 1.0681955 , -1.7326038 ,  0.8301812 ]]], dtype=float32)>

2. tf.unstack(x, `axis`)

In [9]:
result = tf.unstack(x, axis=0)
len(result)

10

# Statistics
## Vector norm
### L1 norm
$$||\vec{x}||_1 = \sum_{i} |x_i|$$

### L2 norm
$$ ||\vec{x}||_2 = \sqrt{\sum_{i}{x_i}^2} $$

### $\infty$ norm
$$ ||\vec{x}||_{\infty}= max_{i}(|x_i|) $$

In [10]:
x = tf.ones([3,3])

In [11]:
# L1 norm
tf.norm(x, ord=1)

<tf.Tensor: id=85, shape=(), dtype=float32, numpy=9.0>

In [12]:
# L2 norm
tf.norm(x, ord=2)

<tf.Tensor: id=90, shape=(), dtype=float32, numpy=3.0>

In [13]:
# Infinity norm
import numpy as np
tf.norm(x, ord=np.inf)

<tf.Tensor: id=94, shape=(), dtype=float32, numpy=1.0>

## Description

In [14]:
x = tf.random.normal([4, 10])

### Max and Min

In [15]:
tf.reduce_max(x, axis=1)

<tf.Tensor: id=102, shape=(4,), dtype=float32, numpy=array([0.50672686, 0.8440412 , 1.3618019 , 1.801574  ], dtype=float32)>

In [16]:
tf.reduce_max(x)

<tf.Tensor: id=104, shape=(), dtype=float32, numpy=1.801574>

In [17]:
tf.reduce_min(x, axis=0)

<tf.Tensor: id=106, shape=(10,), dtype=float32, numpy=
array([-1.2080202 , -0.4390637 , -1.0561498 , -1.2111022 , -0.4704426 ,
       -0.36321747, -0.77497   , -0.7781316 , -1.0217596 , -0.318466  ],
      dtype=float32)>

In [18]:
tf.reduce_min(x)

<tf.Tensor: id=108, shape=(), dtype=float32, numpy=-1.2111022>

### Index Max and Min

In [25]:
tf.argmax(x, axis=1)

<tf.Tensor: id=118, shape=(4,), dtype=int64, numpy=array([5, 9, 4, 4], dtype=int64)>

In [26]:
tf.argmin(x, axis=0)

<tf.Tensor: id=120, shape=(10,), dtype=int64, numpy=array([0, 0, 0, 2, 0, 1, 0, 2, 0, 0], dtype=int64)>

### Mean

In [19]:
tf.reduce_mean(x, axis=1)

<tf.Tensor: id=110, shape=(4,), dtype=float32, numpy=array([-0.6473968 , -0.07483584,  0.02938275,  0.17580307], dtype=float32)>

In [21]:
tf.reduce_mean(x)

<tf.Tensor: id=112, shape=(), dtype=float32, numpy=-0.1292617>

### Sum

In [22]:
tf.reduce_sum(x, axis=1)

<tf.Tensor: id=114, shape=(4,), dtype=float32, numpy=array([-6.473968  , -0.74835837,  0.29382747,  1.7580307 ], dtype=float32)>

In [23]:
tf.reduce_sum(x)

<tf.Tensor: id=116, shape=(), dtype=float32, numpy=-5.170468>

# Comparison
tf.equal(`x`, `y`)

In [27]:
x = tf.random.normal([100, 10])
x = tf.nn.softmax(x, axis=1)
x = tf.argmax(x, axis=1)
x

<tf.Tensor: id=129, shape=(100,), dtype=int64, numpy=
array([5, 3, 8, 9, 8, 3, 1, 3, 3, 2, 1, 8, 0, 3, 6, 2, 2, 3, 5, 8, 4, 1,
       4, 4, 6, 4, 7, 4, 7, 3, 3, 4, 1, 8, 1, 0, 2, 7, 5, 7, 6, 6, 6, 6,
       9, 7, 3, 3, 7, 9, 5, 6, 6, 9, 2, 9, 8, 9, 7, 3, 9, 5, 4, 3, 8, 3,
       6, 0, 9, 8, 7, 7, 3, 7, 2, 4, 8, 3, 6, 0, 4, 0, 4, 6, 1, 8, 6, 5,
       4, 6, 5, 9, 6, 0, 9, 6, 9, 8, 5, 0], dtype=int64)>

In [29]:
y = tf.random.uniform([100], dtype=tf.int64, maxval=10)
y

<tf.Tensor: id=133, shape=(100,), dtype=int64, numpy=
array([8, 2, 6, 0, 4, 6, 5, 0, 3, 5, 7, 2, 2, 4, 2, 4, 6, 4, 7, 8, 9, 8,
       7, 8, 3, 2, 5, 2, 8, 1, 2, 2, 5, 1, 2, 4, 4, 2, 9, 0, 4, 2, 0, 2,
       2, 6, 0, 6, 1, 0, 5, 6, 7, 4, 1, 6, 4, 9, 2, 9, 3, 8, 4, 1, 5, 3,
       3, 3, 1, 0, 3, 9, 4, 1, 9, 4, 4, 2, 1, 6, 7, 9, 6, 5, 8, 6, 7, 4,
       0, 6, 8, 5, 8, 6, 7, 3, 0, 5, 2, 5], dtype=int64)>

In [30]:
tf.equal(x, y)

<tf.Tensor: id=134, shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False])>

In [31]:
tf.math.greater(x, y)

<tf.Tensor: id=135, shape=(100,), dtype=bool, numpy=
array([False,  True,  True,  True,  True, False, False,  True, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True, False,  True, False, False,
        True,  True, False,  True, False,  True,  True,  True, False,
       False,  True, False, False,  True,  True,  True, False, False,
       False, False,  True, False,  True, False,  True,  True, False,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False])>

In [33]:
tf.math.less(x, y)

<tf.Tensor: id=136, shape=(100,), dtype=bool, numpy=
array([ True, False, False, False, False,  True,  True, False, False,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
        True, False,  True, False, False, False, False,  True,  True,
        True,  True, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
        True])>

In [34]:
tf.math.greater_equal(x, y)

<tf.Tensor: id=137, shape=(100,), dtype=bool, numpy=
array([False,  True,  True,  True,  True, False, False,  True,  True,
       False, False,  True, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True, False, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False])>

In [35]:
tf.math.less_equal(x, y)

<tf.Tensor: id=138, shape=(100,), dtype=bool, numpy=
array([ True, False, False, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True,  True,  True, False,
       False, False, False,  True, False,  True, False,  True,  True,
       False, False,  True, False,  True, False, False, False,  True,
        True, False,  True,  True, False, False, False,  True,  True,
        True,  True, False,  True, False,  True, False, False,  True,
        True, False,  True,  True, False, False, False, False, False,
        True])>

In [39]:
tf.math.not_equal(x, y)

<tf.Tensor: id=141, shape=(100,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])>

# Padding and Duplicate

## Padding
tf.pad(`x`, `paddings`)

Syntax: paddings = [[Left padding, Righr Padding], ...]

In [40]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([7,8,9,1])

In [41]:
b = tf.pad(b, [[0,2]])
b

<tf.Tensor: id=145, shape=(6,), dtype=int32, numpy=array([7, 8, 9, 1, 0, 0])>

## Duplicate
tf.tile(x, `mutiples`)

Syntax: `multiples` = [multple_times, ...]

In [42]:
x = tf.random.normal([4, 2, 3, 4])

In [43]:
tf.tile(x, [1, 2, 2, 1])

<tf.Tensor: id=153, shape=(4, 4, 6, 4), dtype=float32, numpy=
array([[[[ 1.1500871 ,  0.1626783 , -0.3350023 ,  0.15035284],
         [-0.8318746 ,  0.61222017,  0.51259947, -0.35725534],
         [ 1.1526914 , -1.1044339 ,  0.38495985,  0.7802771 ],
         [ 1.1500871 ,  0.1626783 , -0.3350023 ,  0.15035284],
         [-0.8318746 ,  0.61222017,  0.51259947, -0.35725534],
         [ 1.1526914 , -1.1044339 ,  0.38495985,  0.7802771 ]],

        [[-0.49615774,  1.5097165 ,  0.4280629 , -0.38392228],
         [ 0.49055305,  1.467512  , -0.63233066, -0.05971597],
         [ 0.0198457 , -0.32127845,  0.27733228,  1.6490916 ],
         [-0.49615774,  1.5097165 ,  0.4280629 , -0.38392228],
         [ 0.49055305,  1.467512  , -0.63233066, -0.05971597],
         [ 0.0198457 , -0.32127845,  0.27733228,  1.6490916 ]],

        [[ 1.1500871 ,  0.1626783 , -0.3350023 ,  0.15035284],
         [-0.8318746 ,  0.61222017,  0.51259947, -0.35725534],
         [ 1.1526914 , -1.1044339 ,  0.38495985,  0.

# Limit the Range of Data

$$ x \in [-\infty, a]$$

In [44]:
x = tf.range(5)
tf.minimum(x, 2)

<tf.Tensor: id=159, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 2, 2])>

$$ x \in [a, +\infty]$$

In [46]:
tf.maximum(x, 2)

<tf.Tensor: id=161, shape=(5,), dtype=int32, numpy=array([2, 2, 2, 3, 4])>

$$ x \in [a, b]$$

In [47]:
tf.clip_by_value(x, 2, 4)

<tf.Tensor: id=165, shape=(5,), dtype=int32, numpy=array([2, 2, 2, 3, 4])>

# Advanced manipulations
## tf.gather
Get data by index

In [48]:
x = tf.random.uniform([4,35,8], maxval=100, dtype=tf.int32)

In [49]:
tf.gather(x, [0,1,3,5,7,19], axis=1)

<tf.Tensor: id=172, shape=(4, 6, 8), dtype=int32, numpy=
array([[[36, 87, 37, 77, 51, 68, 43, 28],
        [75, 82, 14, 49, 66, 43, 76, 17],
        [66, 26, 53, 68, 48, 81, 36, 45],
        [33, 39, 53, 36, 96, 13, 89, 62],
        [44, 68, 15, 83, 28, 12, 90, 56],
        [20, 60, 78, 64,  8, 51, 97,  5]],

       [[62, 28, 53, 25, 83, 87, 66, 85],
        [74, 52, 57, 51, 12, 40, 37, 43],
        [ 4, 34, 62, 21, 32, 85, 61, 55],
        [64, 68, 50, 33, 23, 48,  3, 42],
        [79, 14, 66, 21,  0, 26, 52, 13],
        [37, 73, 84, 30, 96, 48, 77, 44]],

       [[ 2, 12, 52, 29, 78, 78, 16, 64],
        [ 2, 31, 21, 69, 33, 43, 12, 87],
        [10, 70, 80, 98, 60, 77, 29, 99],
        [26, 14, 22, 39, 93, 93, 74,  4],
        [49, 17, 69, 69, 34, 35, 78, 51],
        [98, 37, 43, 27, 24, 45, 17, 42]],

       [[ 4, 25,  3, 82, 49, 67, 34, 65],
        [62, 46, 55, 29, 27,  4, 22, 98],
        [25, 85,  0, 25, 17, 46, 24,  3],
        [48, 58, 76,  2, 30, 97, 52, 93],
        [72, 

In [50]:
tf.gather(x,[2,4], axis=2)

<tf.Tensor: id=175, shape=(4, 35, 2), dtype=int32, numpy=
array([[[37, 51],
        [14, 66],
        [27, 86],
        [53, 48],
        [ 9, 89],
        [53, 96],
        [49, 97],
        [15, 28],
        [90, 10],
        [19, 19],
        [66, 68],
        [89, 57],
        [66, 50],
        [66, 79],
        [57, 46],
        [87, 40],
        [ 6, 79],
        [51, 12],
        [27, 51],
        [78,  8],
        [77, 69],
        [ 9, 75],
        [50, 18],
        [27, 19],
        [95, 59],
        [15, 62],
        [48,  2],
        [19, 62],
        [50, 43],
        [57, 56],
        [43, 23],
        [ 3, 96],
        [30, 12],
        [98,  1],
        [43, 46]],

       [[53, 83],
        [57, 12],
        [16, 21],
        [62, 32],
        [25, 62],
        [50, 23],
        [31, 49],
        [66,  0],
        [18, 96],
        [52, 67],
        [65, 50],
        [53, 66],
        [68, 61],
        [89, 89],
        [30, 51],
        [73, 90],
        [57, 17],
    

## tf.gather_nd
Syntax: tg.gather_hd(x, `[coordinate_1,..., coordinate_n]`)

In [51]:
tf.gather_nd(x, [[1,1], [2,2],[3,3]])

<tf.Tensor: id=177, shape=(3, 8), dtype=int32, numpy=
array([[74, 52, 57, 51, 12, 40, 37, 43],
       [41, 20, 83, 83, 64,  3, 33, 51],
       [25, 85,  0, 25, 17, 46, 24,  3]])>

## tf.boolean_mask
tg.boolean_mask(x, `mask`, `axis`)

In [52]:
tf.boolean_mask(x, [1,0,0,0], axis=0)

<tf.Tensor: id=205, shape=(1, 35, 8), dtype=int32, numpy=
array([[[36, 87, 37, 77, 51, 68, 43, 28],
        [75, 82, 14, 49, 66, 43, 76, 17],
        [ 4, 91, 27, 70, 86, 29, 72, 74],
        [66, 26, 53, 68, 48, 81, 36, 45],
        [74, 39,  9,  5, 89, 42, 22, 27],
        [33, 39, 53, 36, 96, 13, 89, 62],
        [84, 94, 49, 29, 97, 26, 15, 46],
        [44, 68, 15, 83, 28, 12, 90, 56],
        [ 1, 33, 90, 19, 10, 13, 51, 89],
        [10, 44, 19, 35, 19, 27, 69,  6],
        [23, 90, 66,  7, 68, 36, 49, 73],
        [43, 26, 89, 73, 57, 68, 82, 45],
        [91, 11, 66, 84, 50,  5, 19, 84],
        [74, 59, 66, 72, 79, 28, 82, 95],
        [24, 18, 57, 72, 46, 41, 16, 30],
        [19, 74, 87, 23, 40,  7, 38, 42],
        [72, 24,  6, 37, 79, 94, 96, 10],
        [98, 69, 51, 60, 12,  2, 53, 75],
        [ 4, 87, 27, 61, 51, 45, 75, 59],
        [20, 60, 78, 64,  8, 51, 97,  5],
        [79, 88, 77, 25, 69, 33, 95, 90],
        [76, 65,  9, 68, 75, 39, 52, 56],
        [11, 12, 5

In [58]:
x = tf.random.uniform([2,3,8],maxval=100, dtype=tf.int64)

In [60]:
tf.boolean_mask(x, [[1,1,0], [0,1,1]])

<tf.Tensor: id=270, shape=(4, 8), dtype=int64, numpy=
array([[48, 73, 24, 28, 33, 94, 39,  7],
       [20, 44, 34, 28, 67, 87, 37, 75],
       [58, 59, 96,  0, 17, 25, 92, 54],
       [66, 73, 40, 58, 17, 14, 38, 39]], dtype=int64)>

## tf.where
tf.where(`condition`, `a`, `b`):
$$output_i = \begin{cases}
    a_i \qquad & condition_i == True \\
    b_i \qquad & condition_i == False
    \end{cases}$$

In [61]:
a = tf.ones([3,3])
b = tf.zeros([3,3])
cond = tf.constant([[True,0,0],[0,1,0], [1,1,0]])

In [62]:
tf.where(cond, a, b)

InvalidArgumentError: cannot compute SelectV2 as input #0(zero-based) was expected to be a bool tensor but is a int32 tensor [Op:SelectV2]